[c5b788396778][ef5901232414] Introduce individual BrowserView per tab
prometheon/bedrock-electron-2 pull request #21
Opened 2023-01-20 15:27 UTC by omieliekh

2023-01-20 19:00 UTC, digis4eva requested changes

2023-01-20 19:00 UTC, digis4eva commented on src/main/main.ts
> +    offset = _win?.isMaximized()
Seems like _win should already be defined, since you have a check in the beginning of this function, so no need for optional chaining

2023-01-20 19:00 UTC, digis4eva commented on src/main/main.ts
> +  _view?.setBounds({
Same as for _win in this function

2023-01-20 19:00 UTC, digis4eva commented on src/main/main.ts
> +        win?.webContents.send('bedrock-event-pageTitleUpdated', {
No need for optional chaining here

2023-01-20 19:00 UTC, digis4eva commented on src/main/main.ts
> +
Unnecessary empty line

2023-01-20 19:00 UTC, digis4eva commented on src/main/main.ts
> +      createdAt = new Date().getTime(),
Date.now()

2023-01-20 19:00 UTC, digis4eva commented on src/main/main.ts
> +      win?.getBrowserViews()?.forEach((browserView) => {
No need for optional chaining here after win and highly likely after getBrowserViews()

2023-01-20 19:00 UTC, digis4eva commented on src/utils/windowUtils.ts
> +    view?.setBounds({
Can getBrowserViews() really return an array with null or undefined entries?

2023-01-24 16:00 UTC, omieliekh commented on src/main/main.ts
> +        win?.webContents.send('bedrock-event-pageTitleUpdated', {
it could be undefined when event is fired

2023-01-26 18:41 UTC, digis4eva approved these changes

2023-01-27 07:53 UTC, merged