Feat: remove sidebar
prometheon/bedrock-electron-2 pull request #37
Opened 2023-05-31 11:27 UTC by alavren

Linear ticket - https://linear.app/bedrock2/issue/BED-25/remove-sidebar

Connected PR - https://github.com/prometheon/bedrock-fabric/pull/810

- Add new button to tabs with navigation
- Add few more icons to show with new tab button

https://github.com/prometheon/bedrock-electron-2/assets/112943315/7dbb316f-2e09-4ea9-b550-caefcbd4b603

Known issue is that `dataspace.iconUrl` is referring to `upload` folder in `bedroc-fabric` repo so it's not displaying properly as button icon. You can see that at the end of demo record.

2023-05-31 15:49 UTC, Tammerabi approved these changes

2023-05-31 15:55 UTC, Tammerabi requested changes
I think you need to bump the version actually

2023-06-01 12:46 UTC, alavren commented
> I think you need to bump the version actually

Done!

2023-06-01 15:12 UTC, Tammerabi approved these changes

2023-06-01 15:22 UTC, merged